---
name: MooseX-GlobRef
version: 0.07
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Store a Moose object in glob reference
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-GlobRef
  license: http://dev.perl.org/licenses/
  repository: http://code2.0beta.co.uk/moose/svn/MooseX-GlobRef
requires:
  Moose: 0.56
  perl: 5.006
build_requires:
  Test::Assert: 0
  Test::Unit::Lite: 0.12
  parent: 0
provides:
  MooseX::GlobRef:
    file: lib/MooseX/GlobRef.pm
    version: 0.07
  MooseX::GlobRef::Object:
    file: lib/MooseX/GlobRef/Object.pm
    version: 0.07
  MooseX::GlobRef::Role::Meta::Instance:
    file: lib/MooseX/GlobRef/Role/Meta/Instance.pm
    version: 0.07
  MooseX::GlobRef::Role::Object:
    file: lib/MooseX/GlobRef/Role/Object.pm
    version: 0.07
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
